### ISSUE TITLE
Does not account for strange time zones

### ISSUE THREAD

**Issue by triphora** [venashial/chronos#1]
India, Nepal, parts of Australia, New Zealand, North Korea, and dozens of other countries I can't think of off the top of my head do not use the full hour times. You must account for any half-hour times, as well as the +5:45 time in Nepal.
https://github.com/venashial/chronos/blob/main/src/main.rs#L36-L60

**Comment by venashial** [comment]
Discord has a limit of 25 options for application commands which -12 through 12 takes up, so I'm thinking I'll have to add a `/custom` command

**Comment by venashial** [comment]
`/custom` has been added with d83f26b3998d8c1a85ee14091b14d0275dbd5652
